name: flutter_quill_delta_from_html
description: "Convert easily HTML inputs content to Quill Js Delta format"
version: 1.6.0
homepage: https://github.com/Sebastien-VZN/flutter_quill_delta_from_html_robust
repository: https://github.com/Sebastien-VZN/flutter_quill_delta_from_html_robust
issue_tracker: https://github.com/Sebastien-VZN/flutter_quill_delta_from_html_robust/issues
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_quill_delta:
    git:
      url: https://github.com/Sebastien-VZN/dart_quill_delta_robust.git
  html: ^0.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
